sudo: required
language: java
jdk:
  - oraclejdk8
install:
  - npm install --prefix client
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - mvn prepare-package
  - npm test --prefix client
cache:
  directories:
  - $HOME/.m2
  - client/node_modules
after_script:
  - mv target/site/jacoco/jacoco.xml ./
  - sed -i 's_com_server/src/main/java/com_g' jacoco.xml
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.jacoco.json
  - rm jacoco.xml
  - mv client/coverage/lcov.info ./coverage
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.lcov.json
  - ls coverage/*
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage